apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api-deployment
  namespace: contacts-api-namespace # Defines the namespace in which the deployment will be created.
  labels:
    app: contacts-api
spec:
  replicas: 3  # Let's start with 3 instances(pods) of our application.
  selector:
    matchLabels:
      app: contacts-api
  template:
    metadata:
      labels:
        app: contacts-api
    spec:
      containers:
      - name: contacts-api-container
        image: bhardwajnkl/contacts-backend-h2:1.0.1  # Docker image of the application
        resources:
          requests:
            memory: "256Mi"  # Minimum memory request
            cpu: "250m"      # Minimum CPU request
          limits:
            memory: "512Mi"  # Upper memory limit
            cpu: "500m"      # Upper CPU limit
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090  # Port on which the container listens
        livenessProbe:
          httpGet:
            path: /api/contacts/live
            port: 9090
          initialDelaySeconds: 90   # Liveness probe starts after 90 seconds. The app takes around 1 minute to launch.
          periodSeconds: 5          # Liveness check is done every 5 seconds.
          timeoutSeconds: 3         # If the liveness check endpoint does not respond for 3 seconds, we consider it a failure.
          failureThreshold: 3       # If we get 3 consecutive failures, only then that pod will be restarted.
        readinessProbe:
          httpGet:
            path: /api/contacts/ready
            port: 9090
          initialDelaySeconds: 60  # Readiness probe starts after 90 seconds.
          periodSeconds: 3         # Readiness check is done every 3 second until the app is marked ready.
          timeoutSeconds: 3        # If the readiness check endpoint does not respond for 3 seconds, we consider it a failure.
