apiVersion: v1
kind: Service
metadata:
  name: contacts-api-deployment-service
  namespace: contacts-api-namespace
spec:
  selector:
    app: contacts-api
  ports:
    - protocol: TCP
      port: 9090  # Exposed port
      targetPort: 9090  # Container's port
  type: LoadBalancer
